### ISSUE TITLE
Write SFTP guide

### ISSUE THREAD

**Issue by ishantheperson** [CalLavicka/c0-vscode-extension#13]
We need to write a clean guide explaining how to get started with SFTP. 
Slide 15 from [this 213 presentation](https://www.cs.cmu.edu/~213/activities/linux-bootcamp/linux-bootcamp.pdf) is a good start, but we need to make it specific to our course.

**Comment by angelaz1** [comment]
Here's a basic Google Slides presentation to get started on this: https://docs.google.com/presentation/d/1Y3T15cJWumS-a0lOQwwyOhLMF6Yz7YBsbGfrZ0EmaZM/edit?usp=sharing
We can use this during laptop setup/linux sessions at the beginning of the semester :)

**Comment by ishantheperson** [comment]
Thanks!! That's really great. We could just include a link/QR code to it on the setup lab handout

**Comment by ishantheperson** [comment]
@angelaz1 should this issue be closed?

**Comment by ishantheperson** [comment]
Iliano had some comments about this actually

> 
>         - s.2: if one already has an SFTP client installed, do they need to install lixomomo?
>         - s.3: students will make all kinds of mistakes if they are asked to copy some code.
>                 better to give a link where they can download a template that they can update
>                 with their own info.
>         - s.5: please make sure this is the latest version of factorial.c0 .
>         - s.7: I don't think we should emphasize '#use "foo.c0"' -- students make enough mistakes
>                 without knowing about it.  Let it be a silent feature.
>         - s.9: "fibonacci.c0" -> "factorial.c0"
>         - s.13: when hovering over a function, do you get also its contracts?  (This would be really useful!)

**Comment by angelaz1** [comment]
s.2: Good point! In that case, I don't think they need to install the extension. Added that note to the slide!
s.3: Most of this is setup for them when they do "SFTP: Config", and they only need to make a few changes. I'm worried that because this sftp.json file is in a hidden folder, they might actually make more mistakes trying to move/copy over a template file. Should we provide the whole local folder for them, and just have them move it over to wherever on their own computer, then have them fill in their Andrew ID in the sftp.json file?
s.5: I realized this is the F18 version of lab01. I can update the screenshots as soon as we get access to the S20 version!
s.7: Will update this screenshot as well!

**Comment by ishantheperson** [comment]
I definitely agree with you about the config file,  I'm only worried people might forget about download on open. We can probably just post something on Diderot they can copy and paste. It's definitely true that having them download and figure out where to save will be a nuisance

**Comment by angelaz1** [comment]
Slides updated for the most recent version of the extension!
